 spring:
  datasource:
    url: jdbc:mysql://b013b8ad7e4f08:9527582a@eu-cdbr-west-01.cleardb.com/heroku_6f3008cfa06dedf?reconnect=true
    username: b013b8ad7e4f08
    password: 9527582a
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
