spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/begreen
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # servlet:
  #   multipart:
  #     max-file-size: 128KB
  #     max-request-size: 128K

